### ISSUE TITLE
Fehlermeldung oi4-Service

### ISSUE THREAD

**Issue by GoranErdeljan** [GoranErdeljan/TINF19C-Team-4-Service-Registry#1]
Folgende Fehlermeldung erscheint beim Kompilieren des TypeScript-Codes in NodeJS:

> oi4-service@0.11.8 tsc /home/benedict/oi4-registry-0.11.8/OI4-Service

 > tsc
 
src/Application/ConformityValidator/index.ts(7,43): error TS2307: Cannot find module '../../Config/Schemas/schemas/NetworkMessage.schema.json'.

 src/Application/ConformityValidator/index.ts(8,44): error TS2307: Cannot find module '../../Config/Schemas/schemas/MetaDataVersion.schema.json'.

 src/Application/ConformityValidator/index.ts(9,42): error TS2307: Cannot find module '../../Config/Schemas/schemas/oi4Identifier.schema.json'.

 src/Application/ConformityValidator/index.ts(10,43): error TS2307: Cannot find module '../../Config/Schemas/schemas/DataSetMessage.schema.json'.

 src/Application/ConformityValidator/index.ts(11,42): error TS2307: Cannot find module '../../Config/Schemas/schemas/LocalizedText.schema.json'.

 src/Application/ConformityValidator/index.ts(12,38): error TS2307: Cannot find module '../../Config/Schemas/schemas/resources.schema.json'.

 src/Application/ConformityValidator/index.ts(13,40): error TS2307: Cannot find module '../../Config/Schemas/schemas/serviceType.schema.json'.

 src/Application/ConformityValidator/index.ts(16,35): error TS2307: Cannot find module '../../Config/Schemas/schemas/health.schema.json'.

 src/Application/ConformityValidator/index.ts(17,32): error TS2307: Cannot find module '../../Config/Schemas/schemas/mam.schema.json'.

 src/Application/ConformityValidator/index.ts(18,36): error TS2307: Cannot find module '../../Config/Schemas/schemas/license.schema.json'.

 src/Application/ConformityValidator/index.ts(19,40): error TS2307: Cannot find module '../../Config/Schemas/schemas/licenseText.schema.json'.

 src/Application/ConformityValidator/index.ts(20,36): error TS2307: Cannot find module '../../Config/Schemas/schemas/profile.schema.json'.

 src/Application/ConformityValidator/index.ts(21,34): error TS2307: Cannot find module '../../Config/Schemas/schemas/event.schema.json'.

 src/Application/ConformityValidator/index.ts(22,38): error TS2307: Cannot find module '../../Config/Schemas/schemas/rtLicense.schema.json'.

 src/Application/ConformityValidator/index.ts(23,35): error TS2307: Cannot find module '../../Config/Schemas/schemas/config.schema.json'.

 src/Application/ConformityValidator/index.ts(24,44): error TS2307: Cannot find module '../../Config/Schemas/schemas/publicationList.schema.json'.

 src/Application/ConformityValidator/index.ts(25,45): error TS2307: Cannot find module '../../Config/Schemas/schemas/subscriptionList.schema.json'.

 src/Service/Utilities/OPCUABuilder/index.ts(16,43): error TS2307: Cannot find module '../../../Config/Schemas/schemas/NetworkMessage.schema.json'.

 src/Service/Utilities/OPCUABuilder/index.ts(17,44): error TS2307: Cannot find module '../../../Config/Schemas/schemas/MetaDataVersion.schema.json'.

 src/Service/Utilities/OPCUABuilder/index.ts(18,42): error TS2307: Cannot find module '../../../Config/Schemas/schemas/oi4Identifier.schema.json'.

 src/Service/Utilities/OPCUABuilder/index.ts(19,43): error TS2307: Cannot find module '../../../Config/Schemas/schemas/DataSetMessage.schema.json'.

 src/Service/Utilities/OPCUABuilder/index.ts(20,42): error TS2307: Cannot find module '../../../Config/Schemas/schemas/LocalizedText.schema.json'.

 src/Service/Utilities/OPCUABuilder/index.ts(21,38): error TS2307: Cannot find module '../../../Config/Schemas/schemas/resources.schema.json'.

 src/Service/Utilities/OPCUABuilder/index.ts(24,35): error TS2307: Cannot find module '../../../Config/Schemas/schemas/health.schema.json'.

 src/Service/Utilities/OPCUABuilder/index.ts(25,32): error TS2307: Cannot find module '../../../Config/Schemas/schemas/mam.schema.json'.

 src/Service/Utilities/OPCUABuilder/index.ts(26,36): error TS2307: Cannot find module '../../../Config/Schemas/schemas/license.schema.json'.

 src/Service/Utilities/OPCUABuilder/index.ts(27,40): error TS2307: Cannot find module '../../../Config/Schemas/schemas/licenseText.schema.json'.

 src/Service/Utilities/OPCUABuilder/index.ts(28,36): error TS2307: Cannot find module '../../../Config/Schemas/schemas/profile.schema.json'.

 src/Service/Utilities/OPCUABuilder/index.ts(29,34): error TS2307: Cannot find module '../../../Config/Schemas/schemas/event.schema.json'.

 src/Service/Utilities/OPCUABuilder/index.ts(30,38): error TS2307: Cannot find module '../../../Config/Schemas/schemas/rtLicense.schema.json'.

 src/Service/Utilities/OPCUABuilder/index.ts(31,35): error TS2307: Cannot find module '../../../Config/Schemas/schemas/config.schema.json'.

 src/Service/Utilities/OPCUABuilder/index.ts(32,44): error TS2307: Cannot find module '../../../Config/Schemas/schemas/publicationList.schema.json'.

 src/Service/Utilities/OPCUABuilder/index.ts(33,45): error TS2307: Cannot find module '../../../Config/Schemas/schemas/subscriptionList.schema.json'.

**Comment by mrentsch65** [comment]
Die JSON Schemas sind hier abgelegt: https://owncloud.dhbw-stuttgart.de/index.php/s/4tQPRqTQzANssFi

![image](https://user-images.githubusercontent.com/50681355/96254359-74529b00-0fb5-11eb-9d3e-7b0e7def92e4.png)
