### ISSUE TITLE
Erweiterung oder Neuerstellung der OI4-Registry?

### ISSUE THREAD

**Issue by GoranErdeljan** [GoranErdeljan/TINF19C-Team-4-Service-Registry#2]
Sollen wir die bestehende OI4-Registry mit weiteren Features erweitern, oder eine gänzlich neue erstellen?

Falls wir sie erweitern sollen, welche genauen Features sollen hinzugefügt werden?

**Comment by mrentsch65** [comment]
Nach Rücksprache mit der OI4A-Arbeitsgruppe: Im Interesse einer Microservice-Architektur sollte die DNS-SD-Erweiterung als eigenständiges Feature in einer separaten Docker-Applikation untergebracht werden, die mit der OI4-Registry über den MQTT-Messagebus kommuniziert.
