### ISSUE TITLE
Nachrichten-Spezifikation am MQTT-Broker vorhanden ?

### ISSUE THREAD

**Issue by GoranErdeljan** [GoranErdeljan/TINF19C-Team-4-Service-Registry#3]
Gibt es eine Spezifikation, wie das Layout der Nachrichten, die über dem MQTT-Broker angezeigt werden, aussehen soll bzw. wie die Nachrichten aufgebaut sind?

**Comment by mrentsch65** [comment]
Siehe den aktuellen Spezifikationsstand im Anhang:
[Open Industry 4.0 Alliance - Development Guideline_v0.11.pdf](https://github.com/GoranErdeljan/TINF19C-Team-4-Service-Registry/files/5407856/Open.Industry.4.0.Alliance.-.Development.Guideline_v0.11.pdf)

**Comment by mrentsch65** [comment]
Sie müssen auch spezifizieren, wie das Master Asset Model (siehe OI4A Development Guideline) in einem DNS-TXT-Record untergebracht werden kann. Ich empfehle die Codierung als JSON-Objekt.

http://www.zeroconf.org/Rendezvous/txtrecords.html
https://www.rfc-editor.org/rfc/rfc6763.txt

Hier  ein kleines DNS-SD Testtool:
https://www.daemon-systems.org/man/dns-sd.1.html

**Comment by mrentsch65** [comment]
"MetaData": {
    "name": "mam",
    "dataSetClassId": "360ca8f3-5e66-42a2-8f10-9cdf45f4bf58",
    "configurationVersion": {
      "majorVersion": "time_in_seconds_since_the_year_2000 <UINT32>",
      "minorVersion": "time_in_seconds_since_the_year_2000 <UINT32>"
    },
    "description": {
      "locale": "en-US",
      "text": "The Master Asset Set represents the nameplate of a single asset (device, application, ...) as per the Master Asset Model."
    },
    "fields": [
      {
        "name" : "Manufacturer",
        "description" : {
          "locale": "en-US",
          "text": "The name of the manufacturer of an asset. It should be noted that uniformity in the name representation should be a goal, as typically there are different ways of writing a company name regarding all legal appendices etc. In order to avoid shortcomings in identification due to this, the ManufacturerUri is also given."
        },
        "fieldFlags" : 0,
        "builtInType" : 21,
        "dataType" : {
                "ns" : 0,
                "i" : 21
            },
        "valueRank" : -1,
        "maxStringLength" : 0,
        "dataSetFieldId" : "<GUID to define from OI4 if necessary>",
        "properties": {<no properties such as unit, value rage, etc. necessary>}
      },
      {
        "name" : "ManufacturerUri",
        "description" : {
          "locale": "en-US",
          "text": "This property shall provide a valid URI as per RFC 3986. It shall adhere to all rules for an oi4Identifier insofar as the Manufacturer Uri is concerned."
        },
        "fieldFlags" : 0,
        "builtInType" : 12,
        "dataType" : {
                "ns" : 0,
                "i" : 12
            },
        "valueRank" : -1,
        "maxStringLength" : 0,
        "dataSetFieldId" : "<GUID to define from OI4 if necessary>",
        "properties": {<no properties such as unit, value rage, etc. necessary>}
      },
      {
        "name" : "Model",
        "description" : {
          "locale": "en-US",
          "text": "The property Model shall provide the name of the product that the Master Asset information belongs to. Note that model names often are not sufficient to unambiguously identify a product. In order to avoid shortcomings in identification due to this, the ProductC ode is also given. The value given for this property shall also be used for the oi4Identifier of the asset."
        },
        "fieldFlags" : 0,
        "builtInType" : 21,
        "dataType" : {
                "ns" : 0,
                "i" : 21
            },
        "valueRank" : -1,
        "maxStringLength" : 0,
        "dataSetFieldId" : "<GUID to define from OI4 if necessary>",
        "properties": {<no properties such as unit, value rage, etc. necessary>}
      },
      {
        "name" : "ProductCode",
        "description" : {
          "locale": "en-US",
          "text": "A ProductCode has the purpose of unambiguously identifying the model of an asset. Typically, every manufacturer has their own schematics for generating product codes. The ProductCode given for this property shall also be used for the oi4Identifier of the asset."
        },
        "fieldFlags" : 0,
        "builtInType" : 12,
        "dataType" : {
                "ns" : 0,
                "i" : 12
            },
        "valueRank" : -1,
        "maxStringLength" : 0,
        "dataSetFieldId" : "<GUID to define from OI4 if necessary>",
        "properties": {<no properties such as unit, value rage, etc. necessary>}
      },
      {
        "name" : "HardwareRevision",
        "description" : {
          "locale": "en-US",
          "text": "The HardwareRevision shall be given according to the manufacturer-internal revision number of the hardware. If for a physical asset a manufacturer does not have a formalized hardware revision, it shall be set by default to 'undefined'. For any subsequent hardware revisions, this value shall be incremented in an appropriate way. A recommended best practice is to use a dot-separated four numbers schema."
        },
        "fieldFlags" : 0,
        "builtInType" : 12,
        "dataType" : {
                "ns" : 0,
                "i" : 12
            },
        "valueRank" : -1,
        "maxStringLength" : 0,
        "dataSetFieldId" : "<GUID to define from OI4 if necessary>",
        "properties": {<no properties such as unit, value rage, etc. necessary>}
      },
      {
        "name" : "SoftwareRevision",
        "description" : {
          "locale": "en-US",
          "text": "The SoftwareRevision shall be given according to the manufacturer-internal revision number of the software installed on the asset. If for any asset a manufacturer does not have a formalized software revision, it shall be set by default to 'undefined'. For any subsequent software revisions, this value shall be incremented in an appropriate way. A recommended best practice is to use a dot-separated four numbers schema."
        },
        "fieldFlags" : 0,
        "builtInType" : 12,
        "dataType" : {
                "ns" : 0,
                "i" : 12
            },
        "valueRank" : -1,
        "maxStringLength" : 0,
        "dataSetFieldId" : "<GUID to define from OI4 if necessary>",
        "properties": {<no properties such as unit, value rage, etc. necessary>}
      },
      {
        "name" : "DeviceRevision",
        "description" : {
          "locale": "en-US",
          "text": "The DeviceRevision is a conglomerate revision that manufacturers may use to distinguish certain shipment configurations of their device. Typically, a device revision will contain a specific hardware revision and a specific software revision, where the latter may change during the life-cycle through updates."
        },
        "fieldFlags" : 0,
        "builtInType" : 12,
        "dataType" : {
                "ns" : 0,
                "i" : 12
            },
        "valueRank" : -1,
        "maxStringLength" : 0,
        "dataSetFieldId" : "<GUID to define from OI4 if necessary>",
        "properties": {<no properties such as unit, value rage, etc. necessary>}
      },
      {
        "name" : "DeviceManual",
        "description" : {
          "locale": "en-US",
          "text": "A DeviceManual property shall contain a URL that points to a human-readable manual document for the asset. The format of the document is currently unspecified, but a best practice would be a PDF document at the time of the writing of this document."
        },
        "fieldFlags" : 0,
        "builtInType" : 12,
        "dataType" : {
                "ns" : 0,
                "i" : 12
            },
        "valueRank" : -1,
        "maxStringLength" : 0,
        "dataSetFieldId" : "<GUID to define from OI4 if necessary>",
        "properties": {<no properties such as unit, value rage, etc. necessary>}
      },
      {
        "name" : "DeviceClass",
        "description" : {
          "locale": "en-US",
          "text": "This property is a placeholder for storing semantic references regarding the application domain role of the asset in question. Some roles will be defined by OI4 in order to easily administer an OI4 system. Where no such predefined role exists, a semantic referencing framework can be employed to specify the purpose of the asset for the domain in question."
        },
        "fieldFlags" : 0,
        "builtInType" : 12,
        "dataType" : {
                "ns" : 0,
                "i" : 12
            },
        "valueRank" : -1,
        "maxStringLength" : 0,
        "dataSetFieldId" : "<GUID to define from OI4 if necessary>",
        "properties": {<no properties such as unit, value rage, etc. necessary>}
      },
      {
        "name" : "SerialNumber",
        "description" : {
          "locale": "en-US",
          "text": "The serial number shall be a unique identifier for an instance of an asset. It is the manufacturer's responsibility to provide globally-unique serial numbers for all their products. If the assets do not have a unique serial number, the serial number shall begenerated in an appropriate way to be able to have instances of equal types. The SerialNumber given for this property shall also be used for the oi4Identifier of the asset."
        },
        "fieldFlags" : 0,
        "builtInType" : 12,
        "dataType" : {
                "ns" : 0,
                "i" : 12
            },
        "valueRank" : -1,
        "maxStringLength" : 0,
        "dataSetFieldId" : "<GUID to define from OI4 if necessary>",
        "properties": {<no properties such as unit, value rage, etc. necessary>}
      },
      {
        "name" : "ProductInstanceUri",
        "description" : {
          "locale": "en-US",
          "text": "xxxx"
        },
        "fieldFlags" : 0,
        "builtInType" : 12,
        "dataType" : {
                "ns" : 0,
                "i" : 12
            },
        "valueRank" : -1,
        "maxStringLength" : "should that be <maxUrlLength = 255?> instead of <0>?",
        "dataSetFieldId" : "<GUID to define from OI4 if necessary>",
        "properties": {<no properties such as unit, value rage, etc. necessary>}
      },
      {
        "name" : "RevisionCounter",
        "description" : {
          "locale": "en-US",
          "text": "Changes to the configuration of the master asset information shall lead to an increment of the revision counter by one."
        },
        "fieldFlags" : 0,
        "builtInType" : 6,
        "dataType" : {
                "ns" : 0,
                "i" : 6
            },
        "valueRank" : -1,
        "dataSetFieldId" : "<GUID to define from OI4 if necessary>",
        "properties": {<no properties such as unit, value rage, etc. necessary>}
      },
      {
        "name" : "Description",
        "description" : {
          "locale": "en-US",
          "text": "A short localized text as a description can be added here. This object is not defined in OPC UA Part 100, but might be useful for a short overview of the available asset on Open Edge Computing level."
        },
        "fieldFlags" : 0,
        "builtInType" : 21,
        "dataType" : {
                "ns" : 0,
                "i" : 21
            },
        "valueRank" : -1,
        "maxStringLength" : 0,
        "dataSetFieldId" : "<GUID to define from OI4 if necessary>",
        "properties": {<no properties such as unit, value rage, etc. necessary>}
      }
    ]
  }
