### ISSUE TITLE
Richtung der Kommunikation

### ISSUE THREAD

**Issue by wetzelbe** [GoranErdeljan/TINF19C-Team-4-Service-Registry#4]
Sollen nur die per DNS-SD gefundenen Services an der Service Registry aufgelistet werden, oder sollen auch alle anderen in der Registry aufgelisteten Services per DNS-SD beworben werden?

**Comment by mrentsch65** [comment]
Letzteres (alle anderen in der Registry aufgelisteten Services per DNS-SD beworben werden) soll möglich sein, aber per Konfigurationsoption einschaltbar.
